FROM httpd:latest
COPY ./public/welcome.html /usr/local/apache2/htdocs/welcome.html
COPY ./public/css/main.css /usr/local/apache2/htdocs/css/main.css
COPY ./public/dist/bundle.js /usr/local/apache2/htdocs/dist/bundle.js